//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_New
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public string Seotitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyWords { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createDate { get; set; }
        public string ModifiedrBy { get; set; }
        public System.DateTime Modifiedrdate { get; set; }
        public int CategoryId { get; set; }
        public string Alias { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_Category tb_Category { get; set; }
    }
}
